### ISSUE TITLE
Press the button and Numbers changed

### ISSUE THREAD

**Issue by OneGoogus** [Baldhor/Homey-ESPhome-Enhanced#13]
Missing the option to select which button to press, if more then one.

on Number changed, how to select which sensor value I want to trigger on if more then one?

**Comment by Baldhor** [comment]
@OneGoogus When you configure the action (button) or the condition (number), you should be able to select a tag to indicate which one. I sadly do not have multi sensor or multi button device to test it out.

maybe @aedens78 can help with a screenshot, unsure if he use flow

**Comment by OneGoogus** [comment]
I get no option to select on my device. it just say press the button"
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/2384481/ca1db27d-7427-4390-ae35-ba7acab2ba6a)

same goes for trigger. no option. just number changed
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/2384481/210ca5c7-bf30-4aee-966b-e32eae10069f)

**Comment by Baldhor** [comment]
@OneGoogus 
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/b5fb9f47-ba5b-4f1f-94c0-db60017ce678)

Should be this button!

**Comment by Baldhor** [comment]
@OneGoogus I don't know if you solved the issue, but I will not fix it on the current driver, please check the new wizard driver.

Refer to: https://github.com/Baldhor/Homey-ESPhome-Enhanced/issues/12#issuecomment-1680879637
