### ISSUE TITLE
Little aesthetic issues on the settings page

### ISSUE THREAD

**Issue by RoadXY** [Baldhor/Homey-ESPhome-Enhanced#15]
**Your feature request, please describe.**
There is an double line below 'Application settings'.

Line 34, 40, 45, 47, 48, 49, 53 needs i18n (to be translatable)

Link to console.re should open in new window/browser tab.

There is no feedback when the button 'Save changes' is clicked.

**Image**
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/3482284/49d6fa92-4a44-4d93-8122-c5e537d135cd)

**Comment by Baldhor** [comment]
It's still working, but yeah it's a little ugly.
I will probably rework it in the rework branch with the new wizard driver.

**Comment by Baldhor** [comment]
> Link to console.re should open in new window/browser tab.
This part is fixed

**Comment by Baldhor** [comment]
I want to move console.re to the wizard interface instead of settings ...
For me it's kind of easier to maintain only one entry point.
From the user interface, it will be easier to think "everything goes through the wizard".

@RoadXY Any thought?

**Comment by RoadXY** [comment]
Yes, I agree. Much more logical!

**Comment by Baldhor** [comment]
Wiki is updated: https://github.com/Baldhor/Homey-ESPhome-Enhanced/wiki/User-Guide#console-re-page
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/ef57fd0a-c943-4c11-a4f4-1fe90a7c7bdf)

Will publish soon

**Comment by Baldhor** [comment]
Also changed the auto-disable feature to 6 hours, that damned memory leak is still around ...

**Comment by Baldhor** [comment]
puiblished, awaiting certification

**Comment by RoadXY** [comment]
> Also changed the auto-disable feature to 6 hours, that damned memory leak is still around ...

Good solution for now!
