### ISSUE TITLE
screen keeps loading

### ISSUE THREAD

**Issue by Baldhor** [Baldhor/Homey-ESPhome-Enhanced#19]
Hi @Baldhor this fix you pushed is working, I am stuck at a next step.

I can add the device, using a password. I can create a new virtual device, doesn't matter if I change the name or not.

When I try to add any of the functionalities to the virtual device, the screen keeps loading, suggesting me something went wrong.

<img width="1044" alt="Scherm­afbeelding 2023-08-18 om 21 05 09" src="https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/32447944/43bb03e0-6261-4497-8ddd-05f1bffc41f4">

_Originally posted by @JoachimVeulemans in https://github.com/Baldhor/Homey-ESPhome-Enhanced/issues/17#issuecomment-1684331765_

**Comment by Baldhor** [comment]
if if you can try using your computer: my.homey.app
and then open the developper console

![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/82481cc6-cf94-4c9f-acb2-1f6cc2f430e1)

maybe there are some logs there.

Strange enough, once in a while, the drivers (general statement here) fail to operate because of whatever issues on Homey side seems. Sometimes, you just try again and it is solved ...

**Comment by Baldhor** [comment]
@JoachimVeulemans Can you give some details? The issue appear when you click the confirm button at the bottom?

**Comment by JoachimVeulemans** [comment]
@Baldhor 
<img width="540" alt="Scherm­afbeelding 2023-08-19 om 09 32 25" src="https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/32447944/305b79e5-7e3f-42fd-82d7-e6e5442d5460">

**Comment by Baldhor** [comment]
@JoachimVeulemans found the bug, I will publish it in a few.
I made many change to add more logs!

All the logs from the browser will also be sent to console.re!
But I need to filter out passwords first!

**Comment by Baldhor** [comment]
@JoachimVeulemans Published: https://homey.app/fr-fr/app/nl.inversion.esphome/ESPhome/test/

**Comment by Baldhor** [comment]
This is how browser logs will appear now, you can see the password is filtered!
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/dfe126d7-b86a-4aa0-9108-25abf524b5d7)
