### ISSUE TITLE
'number' capability is broken

### ISSUE THREAD

**Issue by Baldhor** [Baldhor/Homey-ESPhome-Enhanced#27]
number capability is broken.
I do not think it is usefull anymore, with the wizard, it's easy to set the title of a capability, and the different capabilities of Homey provide a wide list of 'icon'.

A generic capability like 'number' looks useless to me.
I'd prefer more specific capabilities if the list offered by Homey do not fit a specific need.

**Comment by RoadXY** [comment]
I still think this is useful. 
In example:
On which capability would you set wifi signal or uptime?

If you'd set wifi signal to gas and Athom decided to do 'something smart' with gas, it will give some strange situations...

**Comment by Baldhor** [comment]
They do smart things through deviceClass as far as I know.

Worst case, I would add signal quality capability with its own icon.


Currently the wizard make it easy to change title, unit, capability and
soon deviceClass.
Is it not enough? 😀

Le mer. 23 août 2023, 12:04, Robin van Kekem ***@***.***> a
écrit :
