### ISSUE TITLE
Improved UI

### ISSUE THREAD

**Issue by Baldhor** [Baldhor/Homey-ESPhome-Enhanced#30]
**Is your feature request related to a problem? Please describe.**
To be honest, the Wizard is looking just bad ...
I tried using the homey css style, but the result is just not good.

**Describe the solution you'd like**
I'm thinking about using https://github.com/vuejs/petite-vue.
Try to obtain a result looking like HomeKitty:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/6413b5f2-d173-4100-970c-7575fba064a8)

Basically it means:
- A full rewrite of the views into a single view,
- Backend services used to collect info and apply configuration should be ok.

**Additional features**
At the same time, I think the wizard should allow to match a native capability to several capabilities.
Within a single virtual device or not => the wizard should give a warning, but not an alert (blocking).
However, the same native capability should not be matched several times on the same capability "on a single virtual device".

Examples:
1/ The cover position is used as windowcoverings_set capability.
If "also" matched to a number capability, it could be used to indicate the "<position> %" as a state indicator.

2/ The status of the physical device could be matched to a capability on every virtual device
Same for wifi status ...

**Comment by Baldhor** [comment]
Just a short pick at the state of the improved UI:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/cb8db17d-54f5-4b09-8de4-5ade47416247)

Work is in progress for the virtual device list.

**Comment by RoadXY** [comment]
Nice work, well done!

Could the first screen have explanation, right below the button 'List of physical devices', in the red box (see screenshot below)?
Suggestion for explanation text:
_If you want to add a new physical device, use 'List of virtual device'._

_A physical device is the device it self and can contain one or more virtual devices. 
This way you can split up your device for Homey when you have, for example, a ESPHome device which controls the roller shutters AND has a temperature and humidity sensor connected to it._


![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/3482284/2f947c91-f261-43f6-a4c8-00300b25699f)

**Comment by Baldhor** [comment]
@RoadXY Well the new version of the wizard will allow even more.
Usually with homey : ONE "homey" device **is** ONE physical device.
The current implementation of ESPhome app allows : SEVERAL "homey" devices are **linked** to ONE physicial device
Improved UI will make it one step further : SEVERAL "homey" deviced can be linked to SEVERAL physical devices, AND the same physical device capability can be used several times for different purpose (within the same"homey" device or not) !


Let's for exemple consider a cover, the position state could be used for the windowcoverings_set capability, but also as "measure_current" with unit defined as "%".
The result could be something like:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/ba8e42eb-e8bf-49a1-934c-08903041a885)

You can also imagine to use a capability "measure_poàwer" in "kWH" with precision of 0 (for main page) and another with precision of 3 for a more detailed measure ...

Talking about enhancement request #39, the same native capability could be matched to a "cumulative capability" **and** a "not cumulative capability".

You can imagine a device which list the wifi status of all your ESPhome devices.s


Anyway, I'm very unsure what peoples will do with it, I just do not see any reason to limit it.

**Comment by Baldhor** [comment]
I plan a wiki page with pictures to explain the different screens and what they can do.

**Comment by Baldhor** [comment]
List of virtual device and new physical device are implemented:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/9ff01bc9-2b6f-40b3-9cd9-3d412f865e18)

No idea why but I just cannot retrieve the zone of a device ...
`getDevices()[0].zoneName or zone returns undefined ...`

Connection to the new physical device or failure to do so are fully functionnal (including timeout).
Next step is the ability to edit a virtual device, which is going to be hard work ...

**Comment by Baldhor** [comment]
Renamed the main menu choice, and reviewed the "Manage your virtual devices" view

![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/9b83b34d-63ef-47dd-bc2e-2321cec5a7a8)
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/4a9bcd98-ad38-4952-8ec3-2c0e699d1542)

**Comment by Baldhor** [comment]
New virtual device view is implemented and functionnal:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/2271e0ad-c0b2-443a-8d3d-8f024669eb82)



Next steps:
- edit virtual device view (the most complex)
- and need implement the "update processing" (ie. when an ESPhome configuration change (new entity, removed entity, ...)

**Comment by Baldhor** [comment]
So I'm fully blocked at the moment because of a strange bug in petite-vue:
```
VM20:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertBefore')
    at ze (<anonymous>:1:10577)
    at De (<anonymous>:1:12721)
    at Ge (<anonymous>:1:13472)
    at De (<anonymous>:1:13423)
    at new nt (<anonymous>:1:15203)
    at $ (<anonymous>:1:11192)
    at W.fn (<anonymous>:1:11670)
    at W.run (<anonymous>:1:2309)
    at me (<anonymous>:1:6108)
```

Spent too many hours on it already ...
I oversee only 2 solutions:
1/ Reorganize everything as components, but no idea if it will make the issue disappear
2/ Remove petite-vue ...

**Comment by Baldhor** [comment]
found the root cause of the bug ... moving on

**Comment by Baldhor** [comment]
Working on the capability page (add / edit), it's about 50% done (see below).
It's just missing the input fields to set the capability options, should be straigh forward.

Then it will remains:
- Update processing (when your physical device's native capabilities change!) => just need to pick the existing code
- Ability to save an edited virtual device => not so easy, but mostly copy/paste of existing code
- Ability to delete a capability or a virtual device => easy (hopefully homey api work out as expected :) )
- A welcome page to explain the changes and point to the FAQ => easy
- A FAQ to explain how that crazy thing works ...

![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/e043fb98-2a75-478f-8abd-945eff82ed33)

**Comment by Baldhor** [comment]
Capability page fully implemented, see below.
Tested at 90%, a few bugs left probably.

I added a "hide or show" ability for native capability configs and constraints. It helps keep the page smaller.

![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/239df032-a743-4cd0-b88c-bb45186f981b)

**Comment by RoadXY** [comment]
Wow, nice work! 👍

**Comment by Baldhor** [comment]
A proof it works :)
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/ae380b5f-4b04-4473-9e42-e3ca885a589f)

**Comment by RoadXY** [comment]
Nice 👍
Can't wait to try it out!

**Comment by Baldhor** [comment]
Capability page is fully tested and functionnal.
Just need clean up physical device if they become useless :)

Remaining tasks:
1. Update processing (when your physical device's native capabilities change!) => just need to pick the existing code
2. Ability to save an edited virtual device => easy
3. Ability to delete a capability or a virtual device => easy (hopefully homey api work out as expected :) )
4. A welcome page to explain the changes and point to the FAQ => easy
5. A FAQ to explain how that crazy thing works ...

**Comment by Baldhor** [comment]
Implemented ability to modify the **name**, **zone** and **class** of a device.
see below ...

**However**:
Modification of the **name** and **zone** require to go through the Web API, which require your **bearer token**.

It means I will need to allow setting YOUR bearer token in the app setting screen, and until you do so, the name and zone fields will be "locked".
So I need to implement a "lock" functionnality (how cool).

Thanks Athom BV engineers for your great api consistency ...

![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/e8044985-0d8e-4ad1-8e91-c99bb5e44489)

**Comment by Baldhor** [comment]
Deletion of virtual device implemented, see below.
/!\ require bearer token!

![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/88d057ae-e192-4d5e-98d4-51b5991a6104)

**Comment by RoadXY** [comment]
Nice!
How do you acquire an bearer token?

**Comment by Baldhor** [comment]
> Nice!
> How do you acquire an bearer token?

@RoadXY That's the main issue :

1. Go to : https://my.homey.app/
2. Press F11 (or F12 depends of your browser) to open the developper tool
3. Go to network tab
4. Look for a request with the bearer token in its headers

See pictures
As you can imagine, many users will have issues to find it ...

![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/65ab78ae-b78f-482e-82e6-27e9460bcdd3)

**Comment by Baldhor** [comment]
Deletion of capability is implement.

Added ability to input a bearer token:
1. **Not saved**: the user need to input it everytime he wants to access "advanced" functionnalies
2. Advanced functionnalities are:
-- Modification of a virtual device name or zone
-- Creation of a virtual device in a specific zone, by default it will go into curent zone
-- Deletion of a virtual device directly from the wizard

![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/201167a0-e377-4f90-83c4-29ffcad05b5d)

**Comment by Baldhor** [comment]
@RoadXY I will publish 1.0.0 as beta version if you are willing to test it out :)
Please, expect a few bugs, but it's mostly working!

I will not publish officialy until the welcome pages and a FAQ/Wiki is ready.

**Comment by Baldhor** [comment]
1.0.0 is published **FOR TEST PURPOSE**: https://homey.app/a/nl.inversion.esphome/test/
This thread is closed, please open new issues if you have the courage to test it out :)

**Comment by Baldhor** [comment]
Started a guide: https://github.com/Baldhor/Homey-ESPhome-Enhanced/wiki/About-release-1.0.0

**Comment by RoadXY** [comment]
> > Nice!
> > How do you acquire an bearer token?
> 
> @RoadXY That's the main issue :
> 
> 1. Go to : https://my.homey.app/
> 2. Press F11 (or F12 depends of your browser) to open the developper tool
> 3. Go to network tab
> 4. Look for a request with the bearer token in its headers
> 
> See pictures As you can imagine, many users will have issues to find it ... edit: and the token change "often" (like once every 2 weeks hopefully, but maybe less)
> 
> ![image](https://user-images.githubusercontent.com/57640917/271833339-65ab78ae-b78f-482e-82e6-27e9460bcdd3.png)

The Homey Pro 2023 has an option for creation of an API key local.
The previous models, however, dont.
https://community.homey.app/t/app-pro-dashboards-custom-dashboards-for-your-homey/84837/2?u=robin_van_kekem
