### ISSUE TITLE
No error message when device is unavailable

### ISSUE THREAD

**Issue by RoadXY** [Baldhor/Homey-ESPhome-Enhanced#36]
**Describe the bug**
Undefined error message when device is offline.
I.e. because it is unplugged from the wall or when encryption key is changed/added.

**To Reproduce**
Add encryption key and watch the device become unavailable in Homey.
Open device and see a error message: "Failed connecting to device: undefined"

**Screenshots**
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/3482284/201bb18a-bad3-4795-88ed-c7a25ee0398e)

**Comment by Baldhor** [comment]
Yes, you are right, I do not provide any message to the homey method when the connection is lost after initilization.
I need to think how to implement it, the low level client is scarce in details.

Also, I'm working on a rewrite of the wizard (refer to #30), and so the solution need to consider it.

**Comment by Baldhor** [comment]
Fixed in 1.0.0
