### ISSUE TITLE
Implement mDNS service discovery

### ISSUE THREAD

**Issue by RoadXY** [Baldhor/Homey-ESPhome-Enhanced#37]
**Describe the solution you'd like**
In theory it should be possible to discover ESPHome devices using mDNS
https://apps.developer.homey.app/wireless/wi-fi/discovery#mdns-sd
and
https://esphome.io/components/mdns.html

When adding a new device Homey could try and discover a ESPHome device.
If that fails or times out a manual ip/mDNS/DNS name should used to connect to the device.
mDNS, for example, could fail when using VLAN's in the internal network.

**Comment by Baldhor** [comment]
I was thinking about it, the new wizard with improved UI should be able to provide a "pick me from a discovery list" view.
Hardest work will be to implement the double connection mode, this will impact a lot of code.

And still need to provide a fallback for the user in case his network change ...

**Comment by RoadXY** [comment]
Please see here: https://github.com/Baldhor/Homey-ESPhome-Enhanced/issues/38

**Comment by RoadXY** [comment]
> I was thinking about it, the new wizard with improved UI should be able to provide a "pick me from a discovery list" view. Hardest work will be to implement the double connection mode, this will impact a lot of code.
> 
> And still need to provide a fallback for the user in case his network change ...

When his network changes, mDNS should be able to connect to the device if mDNS was previously used to connect to the device.
If the network changes and IP was used, users are able to go to the settings of that specific device and change the IP address there.

**Comment by Baldhor** [comment]
Let's close this one and use only #38 for now
