### ISSUE TITLE
When adding several capabilities of the same type, only one is added:

### ISSUE THREAD

**Issue by RoadXY** [Baldhor/Homey-ESPhome-Enhanced#40]
When adding several capabilities of the same type, only one is added:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/3482284/5feda642-8cc3-40c0-aa3a-bf5d58976910)

In the devices' settings, all titles of the same capability are the same however I'm 100% positive I had different descriptions for each fase
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/3482284/ab193209-7ba2-410e-aa6c-ec472ea3241e)

_Originally posted by @RoadXY in https://github.com/Baldhor/Homey-ESPhome-Enhanced/issues/35#issuecomment-1715480740_

**Comment by RoadXY** [comment]
https://github.com/Baldhor/Homey-ESPhome-Enhanced/issues/35#issuecomment-1715625885
> > In the devices' settings, all titles of the same capability are the same however I'm 100% positive I had different descriptions for each fase
> 
> Just seen this, you mean you made different title, but the app "forgot" and just used the same title everywhere ... ?

Yes, I tried twice.

**Comment by Baldhor** [comment]
I will test it, but I'm very surprised, as I tested and even posted exemple of multiple capability use.
Maybe a bug introduced later in the development ...

**Comment by Baldhor** [comment]
@RoadXY I just cannot reproduce your issue

Wizard configuration:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/6f3511a1-188f-482e-b692-62a830e3a68e)

Result in homeyu device:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/1ba0ade5-8050-4440-b5db-9f85a03fb9b3)

**Comment by Baldhor** [comment]
One part I don't understand from your screenshot, seems you are using the same native capability twice:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/d3eaa222-91c9-4286-ba4f-1f2a6220365c)

It's not possible in the current wizard (improved-ui will allow it ...).

**Comment by Baldhor** [comment]
PRO TIPS: when on a computer, you can make the driver view larger with the following command:
`while (window.parent.document.querySelector("[data-is-small-view=true]") !== null) {document.querySelector("[data-is-small-view=true]").attributes["data-is-small-view"].nodeValue = "false";}`

Just execute it in the console of the browser

**Comment by RoadXY** [comment]
I will try again to see if I made a mistake

**Comment by RoadXY** [comment]
Well I tried again and... I don't know what went wrong twice but now it's working!
