### ISSUE TITLE
Custom measure capabilities

### ISSUE THREAD

**Issue by Baldhor** [Baldhor/Homey-ESPhome-Enhanced#41]
**Is your feature request related to a problem? Please describe.**
Homey "built in" capabilities are somewhat limited: https://apps-sdk-v3.developer.homey.app/tutorial-device-capabilities.html
Duration, length, angle, weight, ... and probably a few other measure_* capabilities are missing.
The user expect and want an icon that match the meaning of the measure_* capability.

**Describe the solution you'd like**
No choice, need to add some custom capabilities with dedicated icons.
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/a0963a2c-9872-4f15-b4ce-3cbc2b1040fe)
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/c164a32d-ecf5-47f9-af4c-463b43051579)
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/665fe0ef-f67e-4c0b-a044-46958830dd1c)
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/3ac5581e-0295-41f3-a48d-0e9265ab7a90)
...

As a fallback, a generic capbility could be usefull.
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/65764dd4-8daf-4559-9af6-463562301406)

**Comment by Baldhor** [comment]
(and yes, it's a subject discussed with RoadXY a few weeks ago, I just changed my mind lol)

**Comment by RoadXY** [comment]
Maybe make use of the Material Design icons? 
Ronny already uses for his capabilities.
This was added in version 0.2.0 of his app.
This is a diff of version 0.1.9 and 0.2.0
https://github.com/RonnyWinkler/io.home-assistant.community/compare/0.1.9...0.2.0

**Comment by Baldhor** [comment]
Those were just exemple icons, I will check Ronny implementation when the time come (need finish improved-ui first :) )

**Comment by Baldhor** [comment]
So I tried to implelent a "measure_duration" capability.
By default, because it starts with "measure_", it will propose:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/85f90009-bde2-4fc6-88e1-592a2dfa4e6e)

As expected, the other esphome triggers are there too:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/fcc35a4b-6786-4402-a0bb-b22328555846)

> This problem is explained in another thread!

By default, Homey doesn't propose a "value changed" trigger, I need to add it at the driver level,
And then the same constraints as the 4 above will happen, the trigger will appear for all ESPhome virtual device, even if the measure_duration capability is not used ...

The best I could propose is to reuse those 2:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/54e57536-97ce-43cf-9a38-79198c912f72)

<br>

Maybe I can even make it works for Homey standard capabilities!
If so, it means that for exemple considering a measure_humidity capability:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/d59a7b04-e1ea-480d-b1cc-769ce3a4f728)

> The 5 first triggers will works, but not the last 2!

**Comment by Baldhor** [comment]
For a custom measure capability (duration, length and so on), we will end up with:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/2dde73a2-3411-4173-8502-3d79de705ffe)

> The last 2 being useless, they just appear because of homey limitation ...

**Comment by Baldhor** [comment]
@RoadXY Point of view?

**Comment by Baldhor** [comment]
Those 2 have a value of type "string", so the user will need to be carefull :)
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/9fc2eccf-e976-41cc-9123-1cf48a231d38)

> Meaning I will need to handle the conversion from text to number

Maybe later I can send a notification if the user input a text value when a number is expected ...

**Comment by Baldhor** [comment]
Either I go a generic way, or I need go a specific way.
And if I go a specifc way it means poissibly hundreds of cards will appear but should not ...

So I decided to do as I explained in the previous posts => The custom capability esphome_text will actually support ALL the capabilities excepted list of values (enum).
I will test how it work out for float, I'm unsure above the behaviour if the user input . (dot) or , (comma).

**Comment by Baldhor** [comment]
So I have been working around the subject, and I so I implemented the following:

1/ esphome_select is deprecated, in the meatime it will works as esphome_text (see next points)
2/ esphome triggers, condition and action will propose ALL capabilities, whatever their types!
- The action card will not propose the capabilities which are readOnly
3/ esphome triggers, condition and action will propose values dynamically based on the type of the capability selected!
- Default values for specific capabilities will also be proposed
- windowcoverings_set, windowcoverings_tilt_set, dim and volume_set will propose the values "open" and "close"
- windowcoverings_set, windowcoverings_tilt_set, dim and volume_set will propose the value 0.5 (middle) as a default if no valid input
- boolean will propose "true" and "false"
- list of values (enum) will propose list of values :)



A few screenshot:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/721a0d94-88cc-4ed5-ad7e-30faf65ab713)

![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/337dc04c-4e59-40d2-8201-18e59d051d3f)

![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/0ef2adca-c239-4a50-933e-74f667719093)

![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/729cfca3-2285-4a93-aade-437b421c7eb3)

![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/1c69b8ea-c159-43ff-b44c-3b9e37b55524)
> For free text capability, the value the user input will be proposed in the list of available value, making his value valid!

<br>

I think that one worth a few beers lol

**Comment by Baldhor** [comment]
@RoadXY @denstol @Nettopp Opinion?

Can help me test it out if I publish a test version?

**Comment by Baldhor** [comment]
Published as test version, I have good hope it doesn't break anything!
https://homey.app/fr-fr/app/nl.inversion.esphome/ESPhome/test/

**Comment by Baldhor** [comment]
Implemented custom capabilities: measure_angle, measure_length, and measure_weight (not published).

I start to think in the wizard, the default values for precision, min, max, units, ... should appear.
Otheriwse it is confusing ... need to add it to the constant file and implement it.

> Annoying part is that even for standard capabilities, it's like repeating all the conf from Homey in my own file, just cannot access the default manifest from an app ...

**Comment by RoadXY** [comment]
> @RoadXY Point of view?

I'm sorry, I don't understand what you're asking.

**Comment by Baldhor** [comment]
> > @RoadXY Point of view?
> 
> I'm sorry, I don't understand what you're asking.

@RoadXY Yeah in the meantime, I implemented the "context aware" cards which I think solve the problem fully (excepted custom enum which still require custom capabilities to obtain a picker)

**Comment by Baldhor** [comment]
Published, certification will probably be monday.
I close!
