### ISSUE TITLE
Some native capabilities for Athom detection sensor doesn't work

### ISSUE THREAD

**Issue by KaspaMir** [Baldhor/Homey-ESPhome-Enhanced#43]
Hello, I would like to ask if you could add support to new presence sensor from athom.

https://www.athom.tech/blank-1/human-presence-sensor

I was able to add this device manually, only by using IP, but I don´t know how to adopt it like in Home assistant - it´s in this video - https://youtu.be/X0Cien5r8Jc?t=229 - do I have to do it via OTA update manually?

I see all the the entitis exactly the same like in HA, so I configured it the same way, and it works really great!

<img width="591" alt="image" src="https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/145159458/b47dbb08-80f9-4a79-848c-77fc966818cf">

I set PIR sensor to motion alarm, mmWave sensor to contact alarm and occupancy to general alarm. I tried it in a few flow and it works really well!

But the settings I have to do manually via web browser and not in homey app, is it possible to configure it like in HA?

Thank you for your help!

**Comment by Baldhor** [comment]
@KaspaMir I suppose you mean all those configuration:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/e0f2cb7b-7ea0-48c2-8d3a-756a5e88829e

It's kind of at the bottom of my priority list. Not so difficult to access to the web server to modify them ...
However, yes it's on my list. First flows should be able to modify them, and it should be accessible in some ways (either device setting or wizard).
Currently working on improved-ui, and support of Climate component.

**Comment by Baldhor** [comment]
@KaspaMir That said, as far as I know those "configuration" should appear in the native capability list of the wizard, and you should be able to assign them to a virtual device!? no?

**Comment by KaspaMir** [comment]
Thank you! Your app is great now. I am looking forward to future improvements! 

Yes, all the settings appear  in the native capability list, but when I add it as a new virtual device - as a slider - volume or dim, nothing happens. It would be more suitable to add it not a virtual device but as a setting parameter that will appear in advaced settings - slider is not necessary, we can write a number from range e.g. 1-12m detection

![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/145159458/acfad1ad-1a77-4975-b1c7-d41c2ad41777)

**Comment by Baldhor** [comment]
@KaspaMir Yes longer term is to allow to add a native capability as setting or "maintenance action".
In the meantime, you should still be able to add them as capability of a virtual device, and it should work!

Can you describe what exactly doesn't work?

I notice already that the min and step contraints have strange values ...
Possible to collect logs from console.re? I need the "Received new entity" and "Received state for entity" logs as shown in the pictures below.

![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/ab0c77cc-51eb-4881-b119-aedc1daca06a)
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/e9171718-1574-40ba-98cb-f5211ad1aa65)

**Comment by Baldhor** [comment]
No feedback, closing
