### ISSUE TITLE
v1.0.3 - Wizard - My virtual and physical devices aren't shown (can't edit them)

### ISSUE THREAD

**Issue by PeterKawa** [Baldhor/Homey-ESPhome-Enhanced#49]
**Describe the bug**
Wizard - My virtual and physical devices aren't shown, I have 5 of them, and are functioning OK -> with the 'old' previous style wizard it  worked just fine finding, and editing them.
Possibly useful: It don't matter if I add a valid bearer token up front, or not

**To Reproduce**
1. start the wizard
2. go to manage your virtual/physical devices

**Expected behavior**
Able to find and manage my virtual and physical devices

**Screenshots**
![Screenshot from 2023-10-03 16-59-34](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/74005072/72c74fd4-5942-4cec-8b03-5b3c59043178)

![Screenshot from 2023-10-03 16-59-52](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/74005072/aa432454-4f1a-4c2e-b393-9e68524d7914)

My 5 ESPhome devices:
![signal-2023-10-03-163011_002](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/74005072/ecb1ab98-3436-4c27-a94c-18c4c8b87555)

![signal-2023-10-03-170358_002](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/74005072/b9638813-2202-41f0-a6d4-71072db1e2e1)

**Desktop (please complete the following information):**
 - OS: linux Mint 21.2 Cinnamon v.5.8.4
 - Browser both chrome & firefox
 - Version Chrome: Version 117.0.5938.132 (Official Build) unknown (64-bit) / FF: 118.0.1 (64-bit)

**Smartphone (please complete the following information):**
 - Device: Galaxy s9+ SM-G965F
 - OS: Android 10
 - Browser: both chrome & firefox; both in mobile as in desktop mode
 - Version chrome 117.0.5938.140 / FF: 117.1.0 (Build #2015973691), 6f27adebba+, GV: 117.0.1-20230912013654, AS: 117.0

**Comment by Baldhor** [comment]
It's a consequence of #48.
It failed during configuration load, and so the configuration is empty ...

**Comment by PeterKawa** [comment]
Check!
