### ISSUE TITLE
no capabilities in the menu

### ISSUE THREAD

**Issue by Ulysses-nl** [Baldhor/Homey-ESPhome-Enhanced#58]
Hi 

Thanks for creating this awesome app!

I would like to get in touch with you since i cant seem to install it correctly.

I am trying to get It to work to support our community.
but Im having troubles installing the first physical device since it seems that in the capabilities menu i cant select anything.
It might be that i am not seeing something but since i simply do not have the expertise needed for this.

i have been trying for hours but the list seems to be empty.

<img width="509" alt="Screenshot 2023-10-14 at 16 14 12" src="https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/64925375/c40bff17-9d71-4ed6-a7a5-688722866e0e">

**Comment by Baldhor** [comment]
Hello @Ulysses-nl, there are must be a reason for it.
Can you use the collect debug ingo function from the manage your physical devices page?
https://github.com/Baldhor/Homey-ESPhome-Enhanced/wiki/User-Guide#manage-your-physical-devices-page


Do you know which version of the app you have installed currently?

**Comment by Ulysses-nl** [comment]
Thanks for helping Baldhor.

{
  "physicalDeviceId": "Wizard1697358172318",
  "physicalDevice": {
    "physicalDeviceId": "Wizard1697358172318",
    "status": "new",
    "used": false,
    "name": "test",
    "ipAddress": "192.168.1.115",
    "port": "6053",
    "encryptionKey": "<no value>",
    "password": "<no value>",
    "nativeCapabilities": [],
    "rawData": []
  }
}


Homey version 10.0.2
ESPHOME 1.1.13

**Comment by Baldhor** [comment]
@Ulysses-nl well, seems your device doesn't have any native capabilities :)
Like if you uploaded a firmware with only the basic configuration, like this one: https://github.com/Baldhor/Homey-ESPhome-Enhanced/blob/main/esphome-config/esp8285_basic.yml

Can you check your device through a webbrowser ?=> 192.168.1.115

And if you are sure it should have native capabilities, then enable console.re please : https://github.com/Baldhor/Homey-ESPhome-Enhanced/wiki/User-Guide#console-re-page

**Comment by Baldhor** [comment]
Also maybe is it because your entities do not have a name.
For exemple:
```
switch:
  # Relays
  - id: relay1
    platform: gpio
    name: relay1
```

Without a name, this switch would be invisible from the application (not published through the native api of the device)

**Comment by Baldhor** [comment]
@Ulysses-nl No answer, closing, please reopen if needed (or back)

**Comment by Ulysses-nl** [comment]
Hi Baldhor.

thank you for your support.

i had some trouble getting it to work but now it seems to be working.
i had to first get ESPhome working and for this I installed Home Assistant.
There I compiled the code having capabilities and then adding the device to Homey.

Thank you for creating this software and If you are ever in France welcome to drop by the Catfarm Community.
