### ISSUE TITLE
Add version information

### ISSUE THREAD

**Issue by Baldhor** [Baldhor/Homey-ESPhome-Enhanced#59]
Seems obvious, but it's not so easy :)

Anyway, need to include some version information in the Wizard and "collect debug info" function.

It will make it easier to know which version is concerned by an issue ...

**Comment by RoadXY** [comment]
Could any of these be of help?
https://github.com/search?q=homey+version+language%3AJavaScript+&type=code

**Comment by Baldhor** [comment]
Based on it, I suppose all those 5 could be usefull:
```
homey.homeyModelName
homey.softwareVersion
homey.apiVersion
homey.version
homey.manifest.version
```

**Comment by Baldhor** [comment]
The interresting part of the collect debug info currently implemented is that it focus on a single physical device.
Make it easier when the issue is directly related to the integration of a new physical device.

But when the issue is related to a wider issue, it's may not be relevant ...

So need a way to either:
- collect debug info of a "virtual device"
- collect debug info of just "everything"

However, if I propose a "collect all debug info" function", the others look a little useless ...
> The annoying part is that it will be a long file to dive into ...

Maybe proposing all 3 is not so much useless ...

**Comment by Baldhor** [comment]
The best I could do for now is:
```
                'versions': {
                    'platform': this.homey.platform,
                    'platformVersion': this.homey.platformVersion,
                    'version': this.homey.version,
                    'appVersion': this.homey.manifest.version
                },
```

Which add those to the collect debug info function:
```
  "versions": {
    "platform": "local",
    "platformVersion": 1,
    "version": "10.0.2",
    "appVersion": "1.1.29"
  },
```

**Comment by Baldhor** [comment]
closing, but not yet published
