### ISSUE TITLE
Support for Nettop custom enum

### ISSUE THREAD

**Issue by Baldhor** [Baldhor/Homey-ESPhome-Enhanced#66]
@Nettopp helped test many functions, let implement all the custom enum he need for his climate device :)

I need your "collect device info" for your climate device. I'm pretty sure you posted it somewhere, but just cannot find it anymore :)
https://github.com/Baldhor/Homey-ESPhome-Enhanced/wiki/User-Guide#manage-your-physical-devices-page

**Comment by Nettopp** [comment]
@Baldhor Yay! Here is the debug log:
[Debug info.txt](https://github.com/Baldhor/Homey-ESPhome-Enhanced/files/13009379/Debug.info.txt)

**Comment by Baldhor** [comment]
@Nettopp A few questions :)

<br>

**Custom Fan mode:**
```
      {
        "nativeCapabilityId": "290099816:customFanMode",
        "entityId": "290099816",
        "attribut": "customFanMode",
        "entityName": "Panasonic AC",
        "type": "Climate",
        "used": 1,
        "value": "Automatic",
        "configs": {},
        "constraints": {
          "values": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "Automatic"
          ],
          "type": "string"
        },
        "specialCase": null
      },
```
Usefull? Which values you would expect (1, 2, 3, ...) is not very meaningfull :)

<br>

**Swing mode list:**
```
          "supportedSwingModesList": [
            0,
            1,
            2,
            3
          ],
```
Usefull? I think not, you are using horizontal swing mode and vertical swing mode!

<br>

**I will add a custom enum capability for:**
- [ ] Panasonic AC Vertical Swing Mode
- [ ] supportedCustomPresetsList
- [ ] supportedCustomFanModesList (if you need it)
- [ ] supportedSwingModesList (if you need it, but I don't think so)

**Comment by Nettopp** [comment]
> 
> Usefull? Which values you would expect (1, 2, 3, ...) is not very meaningfull :)
> 

Fan mode equals fan speed, from 1 (lowest)  to 5 (highest), and auto. Its the same settings as the remote, no need to change this in my opinion.

> 
> **Swing mode list:**
> 
> ```
>           "supportedSwingModesList": [
>             0,
>             1,
>             2,
>             3
>           ],
> ```
> 
> Usefull? I think not, you are using horizontal swing mode and vertical swing mode!

You are correct, swing mode is not in use for my heat pump. Vertical and horizontal takes its place.

> 
> 
> **I will add a custom enum capability for:**
> 
> * [ ]  Panasonic AC Vertical Swing Mode
> * [ ]  supportedCustomPresetsList
> * [ ]  supportedCustomFanModesList (if you need it)
> * [ ]  supportedSwingModesList (if you need it, but I don't think so)
 
Sounds good! You do not need to add swing mode, but fan mode would be great :)
It would also be great if you could add mode (heat, cool, off, etc). That would be super useful.

**Comment by Baldhor** [comment]
> It would also be great if you could add mode (heat, cool, off, etc). That would be super useful.

You are right, I added horizontal swing mode, stil lneed mode lol => the most important :)

**Comment by Baldhor** [comment]
@Nettopp done: https://homey.app/fr-fr/app/nl.inversion.esphome/ESPhome/test/

If I did it right:
- mode, custom preset, fan mode and vertical swing mode should have a "ESPhome Custom Enum" proposal in the capability page
- If ESPhome Custom E,num is used:
    - A picker will appear in the device with the expected values
    - All the related cards (trigger, condition and action) will allow to choose those capabilities

Happy testing :)

**Comment by Nettopp** [comment]
@Baldhor Great, I'm currently testing! 
I did not get an option for custom enum on "mode", is this implemented?

![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/120424963/41fdd549-66aa-473e-8e34-f6ef222bd220)

**Comment by Baldhor** [comment]
> I did not get an option for custom enum on "mode", is this implemented?

Yes, and I cannot find any reason it wouldn't work out.

What about the 3 others ? fan_mode, vertical_swing and custom preset?

**Comment by Baldhor** [comment]
@Nettopp Found the issue for mode : https://homey.app/fr-fr/app/nl.inversion.esphome/ESPhome/test/

**Comment by Baldhor** [comment]
For info, I added a 'Custom Enum Request' type of issue for further needs: [Custom Enum Request](https://github.com/Baldhor/Homey-ESPhome-Enhanced/issues/new?assignees=Baldhor&labels=custom_enum&projects=&template=custom_enum.md&title=%5BCustom+Enum+Request%5D+xxx)

Some peoples will not like it, but I'm asking for a beer in exchange!

**Comment by Baldhor** [comment]
Time to close this thread!
