### ISSUE TITLE
[Custom Enum Request] Mitsubishi Heavy Industries (MHI) airco

### ISSUE THREAD

**Issue by denstol** [Baldhor/Homey-ESPhome-Enhanced#67]
**Reminder**
Homey doesn't support dynamic capability for 'list of values'.
Every 'list of values' (enumeration) require a specific implementation!
It takes about 10 minutes to do it correctly and imply support in case fix are needed.
It also means that I need to maintain all those custom enum in the long term!

This is discussed in details here: https://github.com/Baldhor/Homey-ESPhome-Enhanced/wiki/Custom-capabilities

**Pay for a Service**
The idea here is not to sell my service for a price, but more likely to say "**Hey, you own me a beer!**".
> Drinking alcohol is bad for your health, ask for help :)

Jump to my paypal and offer me a beer: https://www.paypal.com/paypalme/baldhors
> Price for a beer in France is about 6€ ...

**Implemented for you, but available for ALL**
The custom enum you request will benefit everyone that may have the same need!
Little by little, the list could cover 90% of everyone needs.
> Meaning, no more beer for me in the medium term :(

**Custom enum requested**
Detail here the custom enum you need!
Include a 'collect debug info' file, you can obtain it through the page 'Manage your physical devices' page.
Refer to the User Guide if needed: https://github.com/Baldhor/Homey-ESPhome-Enhanced/wiki/User-Guide#manage-your-physical-devices-page

**Comment by denstol** [comment]
Hi Baldhor, 

We were in contact recently about the Mitsubishi Heavy Industries (MHI) airco's. I would like to make use of your service to implement the dynamic capabilities for my airco's. I think the mode setting is equal to the Panasonic airco, but the Fan Up/Down and Fan Left/Right will be different. 
I attached the debug info file and, of course, for this implementation I will buy you a beer. You know what, I will buy you 2 beers  ;-) One for each dynamic list.

Thanks for your help and let me know if you need more information.

[collect debug info.txt](https://github.com/Baldhor/Homey-ESPhome-Enhanced/files/13047085/collect.debug.info.txt)

**Comment by Baldhor** [comment]
@denstol 
```
          "supportedModesList": [
            0,
            1,
            2,
            3,
            4,
            5
          ],
          "supportedFanModesList": [
            2,
            3,
            4,
            5,
            9
          ],
          "supportedSwingModesList": [
            0,
            1,
            2,
            3
          ],
```

Yeah, the first one "mode" should works, but not the other two I suppose :)

**Comment by Baldhor** [comment]
I checked the specification from ESPhome, should be:
```
          "supportedFanModesList": [
            2, => auto
            3, => low
            4, => medium
            5, => high
            9  => quiet
          ],
          "supportedSwingModesList": [
            0, => off
            1, => both
            2, => vertical
            3  => horizontal
          ],
```

It matches?

**Comment by denstol** [comment]
@Baldhor: copied below snippets from the build in webserver.

Mode:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/24935105/a241ba23-a710-4e3b-957a-de0f2a757712)

Fan Mode Left / Right:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/24935105/5f2ba185-0c12-4b2c-8422-59599f6da91e)
Does this make sense?

Fan Mode Up / Down:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/24935105/535e8b57-52de-4541-b0a3-7a584b49af29)

Maybe I'm mixing things up here

**Comment by denstol** [comment]
Ok, I see them in the list. 
The supportedFanModesList is ok I guess. Don't know what the other one does, but I guess that's ok too ;-)

**Comment by Baldhor** [comment]
@denstol You are right, I missed those 2!
```
      {
        "id": 3539886882,
        "type": "Select",
        "name": "Airco Werkkamer Fan Control Left Right",
        "config": {
          "objectId": "airco_werkkamer_fan_control_left_right",
          "key": 3539886882,
          "name": "Airco Werkkamer Fan Control Left Right",
          "uniqueId": "airco_werkkamerselectairco_werkkamer_fan_control_left_right",
          "icon": "mdi:arrow-left-right",
          "optionsList": [
            "Left",
            "Left/Center",
            "Center",
            "Center/Right",
            "Right",
            "Wide",
            "Spot",
            "Swing"
          ],
          "disabledByDefault": false,
          "entityCategory": 0
        }
      },
      {
        "id": 3884021616,
        "type": "Select",
        "name": "Airco Werkkamer Fan Control Up Down",
        "config": {
          "objectId": "airco_werkkamer_fan_control_up_down",
          "key": 3884021616,
          "name": "Airco Werkkamer Fan Control Up Down",
          "uniqueId": "airco_werkkamerselectairco_werkkamer_fan_control_up_down",
          "icon": "mdi:arrow-up-down",
          "optionsList": [
            "Up",
            "Up/Center",
            "Center/Down",
            "Down",
            "Swing"
          ],
          "disabledByDefault": false,
          "entityCategory": 0
        }
      },
```

_Your airco device has a very long list of native capabilities :)_

**So I will jsut add all 4 of them.**
And aslo implement numeric to string conversion for fanMode, swingMode and preset.

**Comment by denstol** [comment]
Ok, that would be very nice of you.

**Comment by denstol** [comment]
Would you like more beer?

**Comment by Baldhor** [comment]
@denstol Here you go: https://homey.app/fr-fr/app/nl.inversion.esphome/ESPhome/test/

And thanks for the 2 beers!
Just a reminder, I cannot test it fully, but I was as carefull as possible :)

**Comment by denstol** [comment]
@Baldhor Thanks for your swift response. I will test it quickly and give you some feedback.

**Comment by denstol** [comment]
Did some quick testing.
First I created a new virtual device which contained a lot of test, temperature and custom enum capabilities, but unfortunatly, when I clicked on the device in the Homey Android app, the app crashed.
Then I removed all test and temperature sensors, so only the 5 custom enums where left, and this worked. However, apparently the Fan mode was not a custom enum, but a select thing, so I could not test this. The other 4 custom enums were correctly shown in the app. I did not test anything on the physical device, because everybode is sleeping at the moment and I want to give them a good night of sleep l-)

**Comment by denstol** [comment]
I did some quick testing...
I added a new virtual device which contained a lot of text, temperature and all custom enums. Unfortunately when testing this in the Android app, I could not select the virtual device. The app crashed.
So as a second step I removed all test and temperature capabilities and only left the 5 custom enums. This worked better, I could see 4 custom enums and was able to see and change their values. I did not checked on the real airco, because everybody is sleeping here and I want to give them a good night sleep ;-)
The Fan mode, was a select thing, not an enum. But maybe I selected the wrong capability. 

I give it another try tomorrow and will let you know the results.
Thanks for your help so far. It is really appreciated!

**Comment by Baldhor** [comment]
> The Fan mode, was a select thing, not an enum. But maybe I selected the wrong capability.
Fixed, it was missing a value in the numerical to string conversion.

And I think it explain the crash you got!

New version => https://homey.app/fr-fr/app/nl.inversion.esphome/ESPhome/test/

**Comment by denstol** [comment]
You are awesome... Don't you ever sleep ;-)

**Comment by Baldhor** [comment]
> You are awesome... Don't you ever sleep ;-)

Watching a netflix movie on the computer :)

**Comment by denstol** [comment]
Nice. Enjoy your movie ;-)

**Comment by Baldhor** [comment]
@denstol any news?

**Comment by denstol** [comment]
@Baldhor sorry, did not have a chance to test. Will be in the upcoming weekend. I cant keep up with your pace 😉
