### ISSUE TITLE
Error while editing capability

### ISSUE THREAD

**Issue by RoadXY** [Baldhor/Homey-ESPhome-Enhanced#71]
**Describe the bug**
An error message while trying to edit a capability

**To Reproduce**

1. Edit a current virtual device
2. Edit  a current native capability
3. See error message pop up 😊

**Screenshots**
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/3482284/ae088703-afa4-44ae-8156-d9fae3815738)

**Additional context**
You can use the "collect debug info" feature to attach relevant data to the issue: [User Guide](https://github.com/Baldhor/Homey-ESPhome-Enhanced/wiki/User-Guide#manage-your-physical-devices-page)

**Comment by Baldhor** [comment]
@RoadXY I'm surprised I didn't find that bug during my tests, and surprised nobody opened that issue before :)
Fix is live
