### ISSUE TITLE
Homey app store source code link points to wrong url

### ISSUE THREAD

**Issue by RoadXY** [Baldhor/Homey-ESPhome-Enhanced#8]
**Describe the bug**
The link in the Homey app store which should point to the source code of this app currently points to https://github.com/athombv/com.athom.myapp but should point to this repository.

This url is defined here:
https://github.com/Baldhor/Homey-ESPhome-Enhanced/blob/main/app.json#L34

**Expected behavior**
Open a page to this Github repository.

**Screenshots**
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/3482284/10a00ac9-c541-427f-a714-c239ec5ad9f2)

**Comment by Baldhor** [comment]
nice catch
