### ISSUE TITLE
Presence Sensor Support

### ISSUE THREAD

**Issue by gboyd29** [Baldhor/Homey-ESPhome-Enhanced#84]
Do you know if presence sensors are supported? Will there be flows for occupancy, motion, and luminance? 

Please see the following device https://www.athom.tech/blank-1/human-presence-sensor

**Comment by Baldhor** [comment]
@gboyd29 It should mostly work I think, but probably it will also need me to add some code left and right to support it fully.
Should not be a big deal as long as you can provide me the logs.

**Comment by Baldhor** [comment]
@gboyd29 You think you can retreive the yaml configuration file of the device?

**Comment by Baldhor** [comment]
sensor, binarysensor, switch, button, light, text_sensor ... are all supported
So for me it should be fully supported
