### ISSUE TITLE
Decimal configuration seems ignored

### ISSUE THREAD

**Issue by Baldhor** [Baldhor/Homey-ESPhome-Enhanced#9]
Not sure if related, but the amount of decimal places seems to be ignored entirely?

According to the log on my ESPHome/slimmelezer it is reporting these values with these decimals of accuracy:

```
13:47:53	[D]	[sensor:093]	'Power Consumed Phase 1': Sending state 0.48100 kW with 3 decimals of accuracy
13:47:53	[D]	[sensor:093]	'Energy Consumed Tariff 1': Sending state 3375.22803 kWh with 3 decimals of accuracy
13:47:53	[D]	[sensor:093]	'Energy Consumed Tariff 2': Sending state 3789.25708 kWh with 3 decimals of accuracy
```
However, in the Homey web app (in the browser) there are less decimals:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/95985847/a04eed2b-f072-4683-b84b-df86265374c3)
(Only 2 instead of the 3 it should display?)

And the iPhone app is even more confused:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/95985847/31a7c0c1-ccad-4151-8786-19ed423ddd29)
(I'm not even going to count the amount of decimals there)

I have nothing specific set in the ESPHome config about the decimals; This is how I set the device up on the Homey:
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/95985847/92f7b64a-fe22-4b32-b7ff-777143faa8bf)

(The screenshots and the log snippet were taken at different moments, therefore the actual values don't match)

_Originally posted by @aedens78 in https://github.com/Baldhor/Homey-ESPhome-Enhanced/issues/4#issuecomment-1667722223_

**Comment by Baldhor** [comment]
@aedens78 fixed in master
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/ed9274b0-1e96-4072-87eb-0b2b6563fc42)

**Comment by Baldhor** [comment]
I will try to fix this before publishing
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/57640917/09c9abb2-eb09-445e-bc6e-c50b5a442dea)


Not related, but found it while fixing decimals


as for the little story, homey was expecting a number (integer), but the code used to set a string ...

**Comment by Baldhor** [comment]
Version 0.3.4 published, awaiting certification
https://homey.app/fr-fr/app/nl.inversion.esphome/ESPhome/test/

**Comment by aedens78** [comment]
@Baldhor Yes! Looks to be fixed; both the webclient and the iPhone app now show the configured decimals!
(I did remove the device, remove and reinstall the app, and re-added the device to force the update, and now all is well)

![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/95985847/411d13be-7b5b-42aa-b58d-37cccdef4bc6)
![image](https://github.com/Baldhor/Homey-ESPhome-Enhanced/assets/95985847/d1af20b3-7a02-4d77-bfaa-7fd90dbda79e)

Thank you very much for the fast support and the fix! :)

**Comment by Baldhor** [comment]
>> (I did remove the device, remove and reinstall the app, and re-added the device to force the update, and now all is well)
Yeah it would be cool to update capabilities options on reconnection. Re pairing the device break existing flows ...
